language: objective-c
osx_image: xcode9.3

script:

 - set -o pipefail && xcodebuild -project 'AmahiAnywhere.xcodeproj' -scheme 'AmahiAnywhere' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.3,name=iPhone 8' clean test build | xcpretty -c

# before_script:
#         - rvm get head || true # https://github.com/travis-ci/travis-ci/issues/6307

#         - nvm install 6
#         - npm install -g yarn
